[book]
authors = ["MundakaZgz"]
language = "en"
multilingual = false
src = "src"
title = "100 days of Kafka"

[dependencies]
mdbook = { version = "0.4.14", default-features = false }
semver = "1.0.4"

[build] 
create-missing = false

[preprocessor.fs-summary]
# (default: true)
clean-paths = false

# other preprocessors will naturally need to 
# run after the summary has been generated 
[preprocessor.links]
after = ["fs-summary"] 