name: Book creation
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.15'
          # mdbook-version: 'latest'

#      - name: Install latest nightly
#        uses: actions-rs/toolchain@v1
#        with:
#          toolchain: stable
#          override: true
#          components: mdbook-auto-gen-summary

      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book